### PR TITLE
Fetch remote ip list

### PR DESCRIPTION
**Pull request by sarge**
This is an initial approach to freshing IP Ranges.

I have approached it with static and dynamic ranges.

My intention was for this to be a drop in replacement, I do not believe there are any breaking changes to the caddyconfig- perhaps the Json config??

### CODE REVIEW

**Comment by kirsch33** [comment]
hey sarge, would you be interested in being added as a collaborator to this project? Ive briefly reviewed some of your commits lately and you seem to be more knowledgeable than myself in Go, and lately I just havent had the time to maintain this myself, although i do still actively use it for my Caddy instance.

**Comment by sarge** [comment]
Hi @kirsch33, sure happy to help. 

I have tinkered a little with Caddy over the last few years and have written go for a little longer. Happy to offer what I can on your journey too.

It feels like a few other presets is all that this project needs to be feature complete, happy to help with that.

Do you have any other goals for the project?

**Comment by kirsch33** [comment]
Honestly, the things you have suggested as pull request thus far pretty much puts a bow on this project unless something changes moving forward with Caddy.

You are added as a collaborator now.

My only thoughts regarding this PR in general are the following:

1. Can you help me understand why _https://ip-ranges.amazonaws.com/ip-ranges.json_ was chosen as the master IP list as opposed to _https://www.cloudflare.com/ips-v4_  (just using Cloudflare as an example)? What is the significance of the AWS list? 
2. Similiar question to the pre-canned IP lists, what is their origin and are they completely overwritten during the provisioning once the master list is constructed? Since this pre-canned list is hard-coded in, just want to make sure its not something we will need to keep up with in the event that its not entirely overwritten and could be referenced.

**Comment by sarge** [comment]
Great questions,

I happened to be testing the AWS list. I can roll that back, if you have some preference.

The challenge I faced was what to do if the range request failed, or was blocked for some reason? If that did happen and strict mode was used, no requests could be served. There is a choice here about failing open, if the request fails or the format changes things would likely still work for some / most users, or we could fail closed and reject all requests until we have heard from this external resource.

I have some code (I think) to mint the static lists from the current IP ranges.

I do want to make some other changes, I struck a bit of an issue using this within the caddy ingress. It reloads the config often and that was having an issue with the state of the tickers that refresh the ip lists. Caddy does have a mechanism to help reload state in this case, I plan to refactor this to support that.

**Pull request closed without merging**
